name: movies_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-238.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  go_router: ^13.2.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.4
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  stream_transform: ^2.1.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  # easy_localization: ^3.0.4
  # flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
